///|/ Copyright (c) SuperSlicer 2018 - 2025 Durand Rémi @supermerill
///|/ Copyright (c) Prusa Research 2016 - 2023 Pavel Mikuš @Godrak, Vojtěch Bubník @bubnikv, Lukáš Hejl @hejllukas, Lukáš Matěna @lukasmatena
///|/ Copyright (c) Slic3r 2014 - 2015 Alessandro Ranellucci @alranel
///|/ Copyright (c) 2015 Maksim Derbasov @ntfshard
///|/
///|/ ported from lib/Slic3r/Layer.pm:
///|/ Copyright (c) Prusa Research 2016 - 2022 Vojtěch Bubník @bubnikv
///|/ Copyright (c) Slic3r 2011 - 2016 Alessandro Ranellucci @alranel
///|/
///|/ SuperSlicer, PrusaSlicer, Slic3r are released under the terms of the AGPLv3 or higher
///|/ SuperSlicer is released under the terms of the AGPLv3 or higher
///|/
#ifndef slic3r_LayerRegion_hpp_
#define slic3r_LayerRegion_hpp_

#include <cstdint>
#include <map>
#include <set>
#include <string>
#include <unordered_map>
#include <vector>

#include "DataTreeFwd.hpp"
#include "ExtrusionEntityCollection.hpp"
#include "Flow.hpp"
#include "libslic3r.h"
#include "Polyline.hpp"
#include "SurfaceCollection.hpp"

namespace Slic3r {

class ExPolygon;
class PrintObject;
using ExPolygons = std::vector<ExPolygon>;

namespace ApiInternal { struct LayerAccess; }
namespace ApiInternal { struct LayerRegionAccess; }


class LayerRegion : public PluginPropertyContainer
{
    friend struct ApiInternal::LayerAccess;

public:
    [[nodiscard]] Layer*                            layer()         { return m_layer; }
    [[nodiscard]] const Layer*                      layer() const   { return m_layer; }
    [[nodiscard]] const PrintRegion&                region() const  { return *m_region; }

    // collection of surfaces generated by slicing the original geometry
    // divided by type top/bottom/internal
    //@Deprecated, just recompute them from island if you need to check for top/bottom
    [[nodiscard]] const SurfaceCollection&          slices() const { /*assert(surfaces_filled);*/ return m_slices; }

    //// Unspecified fill polygons, used for intersecting when we don't want the infill/perimeter overlap
    //// note: if empty, that means there is no overlap, so you don't need to intersect with it.
    //@Deprecated, use island.
    [[nodiscard]] const ExPolygons&                 fill_no_overlap_expolygons() const { return m_fill_no_overlap_expolygons; }

    // collection of surfaces generated by slicing the original geometry
    // divided by type top/bottom/internal
    //@Deprecated, use island.
    [[nodiscard]] const SurfaceCollection&          fill_surfaces() const { return m_fill_surfaces; }
    //@Deprecated, use island.
    [[nodiscard]] SurfaceCollection&                set_fill_surfaces() { return m_fill_surfaces; }
    
    // Unspecified fill polygons, used for overhang detection ("ensure vertical wall thickness feature")
    // and for re-starting of infills.
    // computed from islands. use islands if it's easier for you.
    //@Deprecated, use island.
    [[nodiscard]] const ExPolygons&                 fill_expolygons() const;

private:
    mutable uint64_t m_cache_fill_expolygons_computed = 0;
    mutable ExPolygons m_cache_fill_expolygons;
    // create my fill_expolygons from all islands that reference me.
    ExPolygons                                     _compute_fill_expolygons() const;

public:
    // collection of polylines representing the unsupported bridge edges
    [[nodiscard]] const Polylines&                  unsupported_bridge_edges() const { return m_unsupported_bridge_edges; }

    void     clear();

    Flow     flow(FlowRole role) const;
    Flow     flow(FlowRole role, double layer_height) const;
    double   bridging_height_avg_mm() const;
    Flow     bridging_flow(FlowRole role, BridgeType force_type = BridgeType::btNone) const;

    void    slices_to_fill_surfaces_clipped(coord_t opening_offset);
    void    prepare_fill_surfaces();

    void    process_external_surfaces(const Layer *lower_layer, const Polygons *lower_layer_covered);
    void    process_external_surfaces_old(const Layer *lower_layer, const Polygons *lower_layer_covered);
    double  infill_area_threshold() const;
    // Trim surfaces by trimming polygons. Used by the elephant foot compensation at the 1st layer.
    void    trim_surfaces(const Polygons &trimming_polygons);
    // Single elephant foot compensation step, used by the elephant foor compensation at the 1st layer.
    // Trim surfaces by trimming polygons (shrunk by an elephant foot compensation step), but don't shrink narrow parts so much that no perimeter would fit.
    void    elephant_foot_compensation_step(const float elephant_foot_compensation_perimeter_step, const Polygons &trimming_polygons);

    void    export_region_slices_to_svg(const char *path) const;
    void    export_region_fill_surfaces_to_svg(const char *path) const;
    // Export to "out/LayerRegion-name-%d.svg" with an increasing index with every export.
    void    export_region_slices_to_svg_debug(const char *name) const;
    void    export_region_fill_surfaces_to_svg_debug(const char *name) const;

    const ExPolygons &get_raw_slices() const { return m_raw_slices; }

    // public destructor to allow unique_ptr
    ~LayerRegion() = default;
protected:
    friend class Layer;
    friend class PrintObject;
    friend struct ApiInternal::LayerRegionAccess;

    LayerRegion(Layer *layer, const PrintRegion *region) : m_layer(layer), m_region(region) {}

private:
    template<typename ThrowOnCancel>
    friend void apply_mm_segmentation(PrintObject& print_object, ThrowOnCancel throw_on_cancel);

    Layer                      *m_layer;
    const PrintRegion          *m_region;

    // Backed up slices before they are split into top/bottom/internal.
    // Only backed up for multi-region layers or layers with elephant foot compensation.
    //FIXME Review whether not to simplify the code by keeping the raw_slices all the time.
    // superslicer -> layer_needs_raw_backup is now true, so evryone has their cache here.
    ExPolygons                  m_raw_slices;

//FIXME make m_slices public for unit tests
public:
    // collection of surfaces generated by slicing the original geometry
    // divided by type top/bottom/internal
    // TODO: separate them per island.
    SurfaceCollection           m_slices;
#if _DEBUG
    bool                        surfaces_filled = false;
#endif
private:
    //// Unspecified fill polygons, used for intersecting when we don't want the infill/perimeter overlap
    //// note: never empty.
    ExPolygons                  m_fill_no_overlap_expolygons;

    // Collection of surfaces for infill generation, created by splitting m_slices by m_fill_expolygons.
    SurfaceCollection           m_fill_surfaces;

    // collection of polylines representing the unsupported bridge edges
    Polylines                   m_unsupported_bridge_edges;
};

//// One LayerIsland may be filled with solid fill, sparse fill, top / bottom fill.
//static constexpr const size_t LayerExtrusionRangesStaticSize = 3;
//using LayerExtrusionRanges =
//#ifdef NDEBUG
//    // To reduce memory allocation in release mode.
//    boost::container::small_vector<LayerExtrusionRange, LayerExtrusionRangesStaticSize>;
//#else // NDEBUG
//    // To ease debugging.
//    std::vector<LayerExtrusionRange>;
//#endif // NDEBUG

using LayerRegionSetCPtrs = std::set<const LayerRegion*>;

// LayerSlice contains one or more LayerIsland objects,
// each LayerIsland containing a set of perimeter extrusions extruded with one particular PrintRegionConfig parameters
// and one or multiple 
// kind of similar as old's LayerIsland
class LayerRegionIsland : public PluginPropertyContainer
{
private:
    friend class Layer;
    //// 0-based extruder, -1 => not set yet (any).
    //// when the LayerRegionIsland will be sorted, if one has infill & peri extrusion with != extruder,
    ////  then it will split into two.
    uint16_t m_extruder_id = uint16_t(-1);

    std::map<ExtrusionRole, ExtrusionEntityCollection> m_extrusion_regions;
    // my regions
    LayerRegionSetCPtrs m_regions;

    // fill surfaces.
    SurfaceCollection m_fill_surfaces;

public:

    //LayerRegionIsland(const LayerRegionSetCPtrs &regions) : m_regions(regions) {}
    LayerRegionIsland(const LayerRegionSetCPtrs &regions, uint16_t extruder_id) : m_regions(regions), m_extruder_id(extruder_id) {}

    static inline ExtrusionRole PERIMETERS = ExtrusionRole::Perimeter;
    static inline ExtrusionRole GAP_FILLS = ExtrusionRole::GapFill;
    static inline ExtrusionRole INFILLS = ERM_Infill;
    static inline ExtrusionRole IRONINGS = ExtrusionRole::Ironing;
    static inline ExtrusionRole MILLS = ExtrusionRole::Milling;
    static inline ExtrusionRole SUPPORT = ExtrusionRole::SupportMaterial;
    static inline ExtrusionRole SUPPORT_INTERFACE = ExtrusionRole::SupportMaterialInterface;


    bool has_extrusion(ExtrusionRole role) const;
    bool has_extrusions() const;
    const ExtrusionEntityCollection &extrusion(ExtrusionRole role) const;

    void remove_empty_extrusions();

    ExtrusionEntityCollection & mutable_extrusion(ExtrusionRole role);

    const LayerRegionSetCPtrs &regions() const { return m_regions; }

    [[nodiscard]] const SurfaceCollection&          fill_surfaces() const { return m_fill_surfaces; }
    [[nodiscard]] SurfaceCollection&                set_fill_surfaces() { return m_fill_surfaces; }

    // @Deprecated this is an algorithm, it should use the LayerRegionIsland, not be inside.
    void simplify_extrusion_entity(const Layer& layer);

    uint16_t extruder_id() const { return m_extruder_id; };

};

} // namespace Slic3r

#endif // slic3r_LayerRegion_hpp_
